# Generated by Django 4.2.7 on 2023-11-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ingredientes', models.TextField(max_length=2000)),
                ('modoPreparo', models.TextField(max_length=8000)),
                ('grauDificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Moderado'), ('D', 'Difícil')], max_length=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceitaApp.categoria')),
            ],
        ),
    ]
