# Generated by Django 4.2.7 on 2023-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0003_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Receita'),
        ),
    ]
