# Generated by Django 4.2.7 on 2023-11-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0004_alter_receita_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Receita'),
        ),
    ]
