# Generated by Django 4.2.7 on 2023-11-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0005_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
